### ISSUE TITLE
oncePerFixture does not run afterEach if last test is skipped

### ISSUE THREAD

**Issue by codambro** [DevExpress/testcafe-once-hook#7]
Looking to use `oncePerFixture` to cleanup after a fixture runs in the case where the last test that normally cleans up is not executed (i.e. through filtering meta data, explicit `test.skip` or `test.only`).

Observed that the oncePerFixture after hook only runs after the last test in the fixture, but if that test is skipped the after hook is not executed.

Simple example:
```
import { oncePerFixture } from "testcafe-once-hook";

const cleanup = oncePerFixture(async () => {
    console.log("Cleanup");
});

fixture("Dummy Fixture").afterEach(cleanup);

test("Dummy test 1", async () => {
    console.log("Dummy test 1");
})

test.skip("Dummy test 2", async () => {
    console.log("Dummy test 2");
})
```

Output (notice no cleanup):
```
 Running tests in:
 - Chrome 112.0.0.0 / Ventura 13

 Dummy Fixture
Dummy test 1
 ✓ Dummy test 1
 - Dummy test 2


 1 passed (3s)
 1 skipped
```

**Comment by codambro** [comment]
This fixes the .skip case. But I don't believe it handles the .only case, or if a custom filter is passed to the TestCafe runner.

**Comment by Artem-Babich** [comment]
Hi, thank you for your interest. I prepared a second pull request for such use cases: [https://github.com/DevExpress/testcafe-once-hook/pull/9](https://github.com/DevExpress/testcafe-once-hook/pull/9)
You'll be able to use it once we release the [testcafe-once-hook](https://github.com/DevExpress/testcafe-once-hook) module.
